// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApm3VjHGejblQCiGGYEN2iziTpCPpk06A',
    appId: '1:402849258843:web:95e78c28480cb75aca0e7e',
    messagingSenderId: '402849258843',
    projectId: 'sign-c78e8',
    authDomain: 'sign-c78e8.firebaseapp.com',
    databaseURL: 'https://sign-c78e8-default-rtdb.firebaseio.com',
    storageBucket: 'sign-c78e8.appspot.com',
    measurementId: 'G-WWJSBZ0C0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe96NXgOfpynw0O2icl8MghU-_r1TE1rs',
    appId: '1:402849258843:android:b2150b91eaffdd63ca0e7e',
    messagingSenderId: '402849258843',
    projectId: 'sign-c78e8',
    databaseURL: 'https://sign-c78e8-default-rtdb.firebaseio.com',
    storageBucket: 'sign-c78e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1qdr5LiaxMd6ymhYhhCWd1qgwjzwV6DU',
    appId: '1:402849258843:ios:512812be61a10fb4ca0e7e',
    messagingSenderId: '402849258843',
    projectId: 'sign-c78e8',
    databaseURL: 'https://sign-c78e8-default-rtdb.firebaseio.com',
    storageBucket: 'sign-c78e8.appspot.com',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1qdr5LiaxMd6ymhYhhCWd1qgwjzwV6DU',
    appId: '1:402849258843:ios:35aa09b667b255e3ca0e7e',
    messagingSenderId: '402849258843',
    projectId: 'sign-c78e8',
    databaseURL: 'https://sign-c78e8-default-rtdb.firebaseio.com',
    storageBucket: 'sign-c78e8.appspot.com',
    iosBundleId: 'com.example.projectMobile.RunnerTests',
  );
}
